py_unit_test(name='dialog',
             srcs=['fdl_test.py',
                   'generation_test.py',
                   'logic_test.py',
                   'parser_test.py',
                   'pilotmodel_test.py',
                   'speechutil_test.py',
                   'test_utils.py'])
