py_unit_test(name='logic_test',
             srcs=['logic_test.py'])

py_unit_test(name='parser_test',
             srcs=['parser_test.py'])

py_unit_test(name='generation_test',
             srcs=['generation_test.py'])

py_unit_test(name='fdl_test',
             srcs=['fdl_test.py'])

py_unit_test(name='speechutil_test',
             srcs=['speechutil_test.py'])

py_unit_test(name='pilotmodel_test',
             srcs=['pilotmodel_test.py'])
