py_unit_test(name='dialog',
             srcs=['logic_test.py',
                   'parser_test.py',
                   'generation_test.py',
                   'fdl_test.py',
                   'speechutil_test.py',
                   'pilotmodel_test.py',
                   ])
